steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v2
    with:
      terraform_version: 1.5.7

  - name: Terraform Init
    run: terraform init
    working-directory: ./infra/tf-app
    
  - name: Terraform Validate
    run: terraform validate
    working-directory: ./infra/tf-app
    
  - name: Terraform Plan
    run: terraform plan -input=false
    working-directory: ./infra/tf-app
    
  - name: Terraform Apply
    run: terraform apply -auto-approve -input=false
    working-directory: ./infra/tf-app