name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  deploy:
    name: Deploy Infrastructure to Azure
    runs-on: ubuntu-latest
    environment: production
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: infra/tf-app

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra/tf-app

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infra/tf-app
